### ISSUE TITLE
Core functionality V0.2.0

### ISSUE THREAD

**Issue by michaelherndon** [nerdymishka/nmfx#3]
- [ ] Support Guard/Check routines in the core library.
- [ ] Support C# 8.0 nullable even for .netstandard2.0
- [ ] Support string case transforms.
