### ISSUE TITLE
CommandLine v0.2.x

### ISSUE THREAD

**Issue by michaelherndon** [nerdymishka/nmfx#4]
- [ ] Enable auto-registration of commands using Managed Extensions Framework.
- [ ] Enhance System.CommandLine
- [ ] Enable spectre.console with System.CommandLine
- [ ] Enable UseStartup() with CommandLineBuilder
- [ ]
